### ISSUE TITLE
PAD: Fix display

### ISSUE THREAD

**Issue by zteeed** [TSPStage/DF#5]
- Correct Typo: « notes avec s »
- Update Title: application de suivi individuel des étudiants 
- Display: rechercher trier button faire un col sm 3 collé sur ladroite value=ok
- Update Value button « ajouter un etudiant a suivre »
- Après ajout de reunion pour un login revenir au profil de letudiant concerné (change redirection path)

**Comment by abracastoral** [comment]
- Correct Typo: fix
- Update Title: done
- Display: fix
- Update Value button « ajouter un etudiant a suivre »: done
- Après ajout de reunion pour un login revenir au profil de letudiant concerné: done
