### ISSUE TITLE
PAD: Fix scripts

### ISSUE THREAD

**Issue by zteeed** [TSPStage/DF#6]
- ajout de fichiers: pas format un pdf (format usuel)
- ajout de fichiers choix du nom faire un placeholder automatique / value
automatique ou marquer que c'est facultatif 
- ajout de fichiers buggés

**Comment by abracastoral** [comment]
- ajout de fichiers: tout format
- ajout de fichier: fix
- download de fichiers buggés (headers invalides ?)

**Comment by zteeed** [comment]
remove include corrigé après analyse a l'editeur hexadécimale
